### PR TITLE
Adds medal skins as actual items

### PR DESCRIPTION
**Pull request by KingDairy**
Because we won't get the medal server, some neat skins can't be accessed unless I do this.

-Satchels are in Crew Quarters. Medical satchels are in the medical lockers above Genetics.
-Inspector's short coat and uniform are in the Detective's locker.
-HOS gets a SWAT gas mask.
-Pilot jumpsuit spawns in the space diner parking lot.
-Dio Brando's outfit appears in a coffin near the old mining station.
-An alchemist left their coat behind in an old tomb.

I couldn't find a good place to put the NTSO items. Badmin, I suppose.

also hi this is my first pr am i doing it right

### CODE REVIEW

**Comment by Shadowlight213** [comment]
I assume you compiled and tested, right? Also the line diff is normal.

**Comment by KingDairy** [comment]
Satchels, the SWAT mask, and the inspector's short coat are missing inhands, but otherwise everything works now.

**Comment by Shadowlight213** [comment]
Ok. I'll test this sometime soon and merge it.

**Comment by Shadowlight213** [comment]
Tested, nothing broke.

**Pull request merged**
